function gui_settings = gui_settings()
    buttons_list = containers.Map;
    buttons_list('i13') = struct('label', 'I13', ...
                            'path', 'S:\Science\I13\Vibration_Monitoring\Processed_Data\',...
                            'description', 'I13-I experimental hutch');
    buttons_list('i14') = struct('label', 'I14', ...
                            'path', 'S:\Science\I14\Vibration_Monitoring\Processed_Data\',...
                            'description', 'I14 experimental hutch');
    buttons_list('z10') = struct('label', 'Zone10', ...
                            'path', '\\dc\dls\science\groups\vibration\20220104_MoundDigging\',...
                            'description', 'Zone 10 temporary digging monitoring (GL72)');                    
    buttons_list('e02') = struct('label', 'E02', ...
                            'path', '\\dc\dls\science\groups\vibration\monitoring\ebic\e02\',...
                            'description', 'eBIC E02 room, under cable tray');
    buttons_list('krios') = struct('label', 'KRIOS', ...
                            'path', '\\dc\dls\science\groups\vibration\monitoring\ebic\krios\',...
                            'description', 'KRIOS hall, inside EM enclosure');

                        
    gui_settings.buttons_list = buttons_list;
end